import React from 'react';
import {
  Play,
  StopCircle,
  Bot,
  MessageSquare,
  Database,
  Code2,
  GitMerge,
  GitBranch,
  FileText,
  Globe,
  RotateCw,
} from 'lucide-react';
import { useFlowStore } from '../hooks/useFlowStore';
import type { AINode, AINodeType } from '../types';

interface ContextMenuProps {
  position: { x: number; y: number };
  onClose: () => void;
  canvasPosition: { x: number; y: number };
  zoom: number;
}

export interface NodeTemplate {
  type: AINodeType;
  label: string;
  icon: React.ReactNode;
  defaultData: any;
}

export const nodeTemplates: NodeTemplate[] = [
  {
    type: 'start',
    label: 'Start',
    icon: <Play size={16} />,
    defaultData: {
      label: 'Start',
      value: '',
      valueType: 'string',
      status: 'idle',
    },
  },
  {
    type: 'stop',
    label: 'Stop',
    icon: <StopCircle size={16} />,
    defaultData: {
      label: 'Stop',
      status: 'idle',
    },
  },
  {
    type: 'ai-agent',
    label: 'AI Agent',
    icon: <Bot size={16} />,
    defaultData: {
      label: 'AI Agent',
      mode: 'text',
      prompt: '',
      instructions: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      maxTokens: 1000,
      status: 'idle',
    },
  },
  {
    type: 'text-generation',
    label: 'Text Generation',
    icon: <MessageSquare size={16} />,
    defaultData: {
      label: 'Text Generation',
      prompt: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      maxTokens: 1000,
      status: 'idle',
    },
  },
  {
    type: 'structured-data',
    label: 'Structured Data',
    icon: <Database size={16} />,
    defaultData: {
      label: 'Structured Data',
      prompt: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      schemaName: '',
      status: 'idle',
    },
  },
  {
    type: 'transform',
    label: 'Transform',
    icon: <Code2 size={16} />,
    defaultData: {
      label: 'Transform',
      transformCode: '// Transform code here\nreturn input;',
      status: 'idle',
    },
  },
  {
    type: 'merge',
    label: 'Merge',
    icon: <GitMerge size={16} />,
    defaultData: {
      label: 'Merge',
      mergeStrategy: 'object',
      status: 'idle',
    },
  },
  {
    type: 'condition',
    label: 'Condition',
    icon: <GitBranch size={16} />,
    defaultData: {
      label: 'Condition',
      conditionType: 'length',
      conditionValue: 100,
      status: 'idle',
    },
  },
  {
    type: 'template',
    label: 'Template',
    icon: <FileText size={16} />,
    defaultData: {
      label: 'Template',
      template: 'Use {{input}} to insert data here...',
      status: 'idle',
    },
  },
  {
    type: 'http-request',
    label: 'HTTP Request',
    icon: <Globe size={16} />,
    defaultData: {
      label: 'HTTP Request',
      url: '',
      method: 'GET',
      headers: {},
      status: 'idle',
    },
  },
  {
    type: 'loop',
    label: 'Loop',
    icon: <RotateCw size={16} />,
    defaultData: {
      label: 'Loop',
      loopType: 'count',
      count: 5,
      status: 'idle',
    },
  },
];

export const ContextMenu: React.FC<ContextMenuProps> = ({
  position,
  onClose,
  canvasPosition,
  zoom,
}) => {
  const addNode = useFlowStore((state) => state.addNode);
  const nodes = useFlowStore((state) => state.nodes);

  const handleAddNode = (template: NodeTemplate) => {
    // Convert screen coordinates to canvas coordinates
    const x = (position.x - canvasPosition.x) / zoom;
    const y = (position.y - canvasPosition.y) / zoom;

    // Auto-generate node name
    const existingNodesOfType = nodes.filter(n => n.type === template.type);
    const nodeNumber = existingNodesOfType.length + 1;
    const autoGeneratedName = `${template.label.toLowerCase().replace(/\s+/g, '-')}-${nodeNumber}`;

    const newNode: AINode = {
      id: `${template.type}-${Date.now()}`,
      type: template.type,
      position: { x, y },
      data: {
        ...template.defaultData,
        name: autoGeneratedName,
      },
    };

    addNode(newNode);
    onClose();
  };

  return (
    <div
      className="gothic-panel"
      style={{
        position: 'fixed',
        top: position.y,
        left: position.x,
        zIndex: 1000,
        minWidth: '200px',
        padding: '8px',
      }}
      onClick={(e) => e.stopPropagation()}
    >
      <div
        style={{
          fontFamily: 'var(--font-primary)',
          fontSize: '11px',
          color: 'var(--cyber-neon-purple)',
          textTransform: 'uppercase',
          letterSpacing: '1px',
          marginBottom: '8px',
          paddingLeft: '8px',
        }}
      >
        Add Node
      </div>

      {nodeTemplates.map((template) => (
        <button
          key={template.type}
          onClick={() => handleAddNode(template)}
          className="node-toolbar-button"
          style={{
            width: '100%',
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            padding: '10px 12px',
            marginBottom: '4px',
            textAlign: 'left',
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
          }}
        >
          {template.icon}
          {template.label}
        </button>
      ))}
    </div>
  );
};
