import React from 'react';
import {
  Play,
  StopCircle,
  Bot,
  MessageSquare,
  Database,
  Code2,
  GitMerge,
  GitBranch,
  FileText,
  Globe,
  RotateCw,
  Upload,
} from 'lucide-react';
import { useFlowStore } from '../hooks/useFlowStore';
import type { AINode, AINodeType } from '../types';

interface ContextMenuProps {
  position: { x: number; y: number };
  onClose: () => void;
  canvasPosition: { x: number; y: number };
  zoom: number;
}

export interface NodeTemplate {
  type: AINodeType;
  label: string;
  icon: React.ReactNode;
  defaultData: any;
}

export const nodeTemplates: NodeTemplate[] = [
  {
    type: 'start',
    label: 'Start',
    icon: <Play size={16} />,
    defaultData: {
      label: 'Start',
      value: '',
      valueType: 'string',
      status: 'idle',
    },
  },
  {
    type: 'stop',
    label: 'Stop',
    icon: <StopCircle size={16} />,
    defaultData: {
      label: 'Stop',
      status: 'idle',
    },
  },
  {
    type: 'ai-agent',
    label: 'AI Agent',
    icon: <Bot size={16} />,
    defaultData: {
      label: 'AI Agent',
      mode: 'text',
      prompt: '',
      instructions: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      maxTokens: 1000,
      status: 'idle',
    },
  },
  {
    type: 'text-generation',
    label: 'Text Generation',
    icon: <MessageSquare size={16} />,
    defaultData: {
      label: 'Text Generation',
      prompt: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      maxTokens: 1000,
      status: 'idle',
    },
  },
  {
    type: 'structured-data',
    label: 'Structured Data',
    icon: <Database size={16} />,
    defaultData: {
      label: 'Structured Data',
      prompt: '',
      model: 'gpt-4o-mini',
      temperature: 0.7,
      schemaName: '',
      status: 'idle',
    },
  },
  {
    type: 'transform',
    label: 'Transform',
    icon: <Code2 size={16} />,
    defaultData: {
      label: 'Transform',
      transformCode: '// Transform code here\nreturn input;',
      status: 'idle',
    },
  },
  {
    type: 'merge',
    label: 'Merge',
    icon: <GitMerge size={16} />,
    defaultData: {
      label: 'Merge',
      mergeStrategy: 'object',
      status: 'idle',
    },
  },
  {
    type: 'condition',
    label: 'Condition',
    icon: <GitBranch size={16} />,
    defaultData: {
      label: 'Condition',
      conditionType: 'length',
      conditionValue: 100,
      status: 'idle',
    },
  },
  {
    type: 'template',
    label: 'Template',
    icon: <FileText size={16} />,
    defaultData: {
      label: 'Template',
      template: 'Use {{input}} to insert data here...',
      status: 'idle',
    },
  },
  {
    type: 'http-request',
    label: 'HTTP Request',
    icon: <Globe size={16} />,
    defaultData: {
      label: 'HTTP Request',
      url: '',
      method: 'GET',
      headers: {},
      status: 'idle',
    },
  },
  {
    type: 'file-upload',
    label: 'File Upload Test',
    icon: <Upload size={16} />,
    defaultData: {
      label: 'File Upload Test',
      status: 'idle',
      files: [],
    },
  },
  {
    type: 'loop',
    label: 'Loop',
    icon: <RotateCw size={16} />,
    defaultData: {
      label: 'Loop',
      loopType: 'count',
      count: 5,
      status: 'idle',
    },
  },
];

export const ContextMenu: React.FC<ContextMenuProps> = ({
  position,
  onClose,
  canvasPosition,
  zoom,
}) => {
  const addNode = useFlowStore((state) => state.addNode);
  const nodes = useFlowStore((state) => state.nodes);

  const handleAddNode = (template: NodeTemplate) => {
    // Convert screen coordinates to canvas coordinates
    const x = (position.x - canvasPosition.x) / zoom;
    const y = (position.y - canvasPosition.y) / zoom;

    // Auto-generate node name
    const existingNodesOfType = nodes.filter(n => n.type === template.type);
    const nodeNumber = existingNodesOfType.length + 1;
    const autoGeneratedName = `${template.label.toLowerCase().replace(/\s+/g, '-')}-${nodeNumber}`;

    const newNode: AINode = {
      id: `${template.type}-${Date.now()}`,
      type: template.type,
      position: { x, y },
      data: {
        ...template.defaultData,
        name: autoGeneratedName,
      },
    };

    addNode(newNode);
    onClose();
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: position.y,
        left: position.x,
        zIndex: 1000,
        minWidth: '240px',
        maxWidth: '300px',
        background: 'linear-gradient(135deg, var(--gothic-charcoal) 0%, var(--gothic-slate) 100%)',
        border: 'var(--border-glow) solid var(--cyber-neon-purple)',
        borderRadius: '8px',
        boxShadow: 'var(--node-shadow)',
        overflow: 'hidden',
        fontFamily: 'var(--font-primary)',
      }}
      onClick={(e) => e.stopPropagation()}
      onMouseEnter={(e) => {
        e.currentTarget.style.boxShadow = '0 0 30px rgba(176, 38, 255, 0.5)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.boxShadow = 'var(--node-shadow)';
      }}
    >
      {/* Header - Matching node header style */}
      <div
        style={{
          background: 'linear-gradient(90deg, var(--gothic-slate) 0%, var(--gothic-gray) 100%)',
          borderBottom: '1px solid var(--cyber-neon-purple)',
          padding: '12px 16px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
        }}
      >
        <div
          style={{
            fontSize: '13px',
            fontFamily: 'var(--font-primary)',
            fontWeight: 700,
            color: 'var(--cyber-neon-cyan)',
            textTransform: 'uppercase',
            letterSpacing: '1px',
            flex: 1,
          }}
        >
          Add Node
        </div>
      </div>

      {/* Menu Items - Styled like node content */}
      <div
        style={{
          padding: '8px',
          maxHeight: '400px',
          overflowY: 'auto',
        }}
      >
        {nodeTemplates.map((template, index) => (
          <button
            key={template.type}
            onClick={() => handleAddNode(template)}
            style={{
              width: '100%',
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              padding: '12px 12px',
              marginBottom: index < nodeTemplates.length - 1 ? '4px' : '0',
              textAlign: 'left',
              background: 'transparent',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
              color: 'var(--cyber-neon-cyan)',
              fontFamily: 'var(--font-geist-sans, "Geist", "Inter", -apple-system, BlinkMacSystemFont, sans-serif)',
              fontSize: '13px',
              fontWeight: 500,
              letterSpacing: '0.01em',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = 'rgba(176, 38, 255, 0.15)';
              e.currentTarget.style.boxShadow = '0 0 10px rgba(176, 38, 255, 0.2)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'transparent';
              e.currentTarget.style.boxShadow = 'none';
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '20px',
                height: '20px',
                color: 'var(--cyber-neon-cyan)',
                filter: 'drop-shadow(0 0 3px currentColor)',
              }}
            >
              {template.icon}
            </div>
            <span
              style={{
                flex: 1,
                color: 'inherit',
                fontFamily: 'inherit',
                fontSize: 'inherit',
                fontWeight: 'inherit',
              }}
            >
              {template.label}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
};
